ros:
  OUXT-Polaris:
    - pcl_apps
    - image_processing_utils
    - scan_segmentation
    - perception_bringup
    - hermite_path_planner
    - behavior_tree_action_builder
    - robotx_behavior_tree
    - color_names
    - quaternion_operation
    - data_buffer
    - geometry_msgs_data_buffer
    - wamv_description
    - geographic_info
    - geographic_conversion
    - nmea_to_geopose
    - pf_localization
    - odom_frame_publisher
    - nmea_gps_driver
others:
  OUXT-Polaris:
    - robotx_setup