name: publish-report
on:
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish-report:
    name: Publish Report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Install Depends
        run: pip3 install requirements.txt
      - name: Generate Report
        run: python3 report.py ${{ secrets.TOKEN }} packages.yaml